'use client'

import { useEffect, useMemo, useState } from 'react'
import { apiFetch } from '../../../lib/api'

type Incident={id:string;status:string;severity:string;title:string;source:string;resourceId:string;startedAt:string;acknowledgedAt?:string;resolvedAt?:string}

export default function IncidentsPage(){
 const [items,setItems]=useState<Incident[]>([]); const [status,setStatus]=useState(''); const [severity,setSeverity]=useState(''); const [loading,setLoading]=useState(true)
 const load=async()=>{setLoading(true); try{const q=new URLSearchParams(); if(status)q.set('status',status);if(severity)q.set('severity',severity);setItems(await apiFetch<Incident[]>(`/api/incidents?${q}`))}catch{/* keep last list */}finally{setLoading(false)}}
 useEffect(()=>{load()},[status,severity])
 const counts=useMemo(()=>({critical:items.filter(i=>i.severity==='critical'&&i.status!=='resolved').length,open:items.filter(i=>i.status==='open').length,ack:items.filter(i=>i.status==='acknowledged').length}),[items])
 const action=async(id:string,a:'acknowledge'|'resolve')=>{await apiFetch(`/api/incidents/${encodeURIComponent(id)}/${a}`,{method:'POST'});load()}
 return <main className="min-h-screen p-6 md:p-8 space-y-6"><header><p className="text-xs font-semibold uppercase tracking-[.2em] text-muted-foreground">Network Operations Center</p><h1 className="text-3xl font-bold tracking-tight">Incidents</h1><p className="text-muted-foreground">Live operational events requiring attention.</p></header>
 <section className="grid grid-cols-1 sm:grid-cols-3 gap-4"><Card label="Critical" value={counts.critical}/><Card label="Open" value={counts.open}/><Card label="Acknowledged" value={counts.ack}/></section>
 <section className="flex flex-wrap gap-3"><select className="rounded-lg border bg-background px-3 py-2" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option><option value="open">Open</option><option value="acknowledged">Acknowledged</option><option value="resolved">Resolved</option></select><select className="rounded-lg border bg-background px-3 py-2" value={severity} onChange={e=>setSeverity(e.target.value)}><option value="">All severities</option><option value="critical">Critical</option><option value="warning">Warning</option><option value="info">Info</option></select></section>
 <section className="rounded-xl border overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-muted/40"><tr><th className="text-left p-4">Incident</th><th className="text-left p-4">Severity</th><th className="text-left p-4">Status</th><th className="text-left p-4">Resource</th><th className="text-left p-4">Started</th><th className="p-4 text-right">Actions</th></tr></thead><tbody>{loading?<tr><td colSpan={6} className="p-8 text-center text-muted-foreground">Loading incidents…</td></tr>:items.length===0?<tr><td colSpan={6} className="p-8 text-center text-muted-foreground">No incidents found.</td></tr>:items.map(i=><tr key={i.id} className="border-t"><td className="p-4"><div className="font-medium">{i.title}</div><div className="text-xs text-muted-foreground">{i.source} · {i.id}</div></td><td className="p-4"><Badge value={i.severity}/></td><td className="p-4"><Badge value={i.status}/></td><td className="p-4 font-mono text-xs">{i.resourceId}</td><td className="p-4 text-muted-foreground">{new Date(i.startedAt).toLocaleString()}</td><td className="p-4 text-right space-x-2">{i.status==='open'&&<button className="rounded-md border px-3 py-1.5" onClick={()=>action(i.id,'acknowledge')}>Acknowledge</button>}{i.status!=='resolved'&&<button className="rounded-md bg-primary text-primary-foreground px-3 py-1.5" onClick={()=>action(i.id,'resolve')}>Resolve</button>}</td></tr>)}</tbody></table></div></section></main>
}
function Card({label,value}:{label:string;value:number}){return <div className="rounded-xl border p-5"><div className="text-sm text-muted-foreground">{label}</div><div className="mt-2 text-3xl font-bold">{value}</div></div>}
function Badge({value}:{value:string}){return <span className="inline-flex rounded-full border px-2.5 py-1 text-xs font-medium capitalize">{value}</span>}
