'use client'

import { useEffect, useMemo, useState } from 'react'
import { MetricChart } from '../../../../components/metric-chart'

type ONU={id:string;name:string;serial:string;status:string;rxPowerDbm?:number;txPowerDbm?:number;los?:boolean}
type PON={id:string;port:number;status:string;onus:ONU[]}
type Hierarchy={oltId:string;name:string;model?:string;pons:PON[];updatedAt:string}
type RuntimeState={oltId:string;running:boolean;startedAt?:string;lastPollAt?:string;lastError?:string;pollCount:number}
type Alert={id:string;olt_id:string;pon_id?:string;onu_id?:string;code:string;severity:string;message:string;value?:number;status:string;first_seen:string;last_seen:string}
type OLTDetailProps={params:Promise<{id:string}>}

const badge=(value:string)=>value==='critical'?'bg-red-950 text-red-300 border-red-900':value==='warning'?'bg-amber-950 text-amber-300 border-amber-900':'bg-slate-800 text-slate-300 border-slate-700'

export default function OLTDetail({params}:OLTDetailProps){
 const [id,setId]=useState(''),[data,setData]=useState<Hierarchy|null>(null),[runtime,setRuntime]=useState<RuntimeState|null>(null),[alerts,setAlerts]=useState<Alert[]>([]),[error,setError]=useState(''),[filter,setFilter]=useState('all'),[busy,setBusy]=useState(true),[expandedOnu,setExpandedOnu]=useState<string|null>(null)
 useEffect(()=>{let live=true;const load=async()=>{try{const p=await params;if(live)setId(p.id);const [h,rt,a]=await Promise.all([fetch(`/api/olts/${encodeURIComponent(p.id)}`,{cache:'no-store'}),fetch('/api/v1/olt/runtime',{cache:'no-store'}),fetch(`/api/v1/olts/${encodeURIComponent(p.id)}/alerts?limit=50`,{cache:'no-store'})]);if(!h.ok)throw Error('OLT not found');const hj=await h.json();const rj=rt.ok?await rt.json():{olts:[]};const aj=a.ok?await a.json():[];if(live){setData(hj);setRuntime((rj.olts||[]).find((x:RuntimeState)=>x.oltId===p.id)||null);setAlerts(Array.isArray(aj)?aj:[]);setError('')}}catch(e){if(live)setError(e instanceof Error?e.message:'Unable to load OLT')}finally{if(live)setBusy(false)}};load();const t=setInterval(load,15000);return()=>{live=false;clearInterval(t)}},[params])
 const onus=useMemo(()=>data?.pons.flatMap(p=>p.onus.map(o=>({...o,pon:p.port}))).filter(o=>filter==='all'||o.status===filter)||[],[data,filter])
 const total=data?.pons.reduce((n,p)=>n+p.onus.length,0)||0
 const online=data?.pons.reduce((n,p)=>n+p.onus.filter(o=>o.status==='online').length,0)||0
 const openAlerts=alerts.filter(a=>a.status==='open'),critical=openAlerts.filter(a=>a.severity==='critical').length,warning=openAlerts.filter(a=>a.severity==='warning').length
 if(error)return <main className="mx-auto max-w-7xl p-6 md:p-8"><div className="rounded-xl border border-red-900 bg-red-950/30 p-6 text-red-300">{error}</div></main>
 if(busy&&!data)return <main className="mx-auto max-w-7xl p-6 md:p-8 text-slate-400">Loading OLT telemetry…</main>
 if(!data)return null
 return <main className="mx-auto max-w-7xl space-y-6 p-6 md:p-8">
  <header className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-cyan-400">Fiber Operations / Live Telemetry</p><h1 className="mt-2 text-3xl font-bold">{data.name}</h1><p className="mt-2 text-sm text-slate-400">{data.model||'OLT'} · {data.oltId||id} · refreshed every 15s</p></div><div className={`rounded-xl border px-4 py-3 text-sm ${runtime?.running?'border-emerald-900 bg-emerald-950/30 text-emerald-300':'border-amber-900 bg-amber-950/30 text-amber-300'}`}><b>{runtime?.running?'● Poller running':'● Poller stopped'}</b><div className="mt-1 text-xs opacity-80">{runtime?.lastPollAt?`Last poll ${new Date(runtime.lastPollAt).toLocaleString()}`:'No successful poll recorded'}{runtime?.pollCount!==undefined?` · ${runtime.pollCount} polls`:''}</div>{runtime?.lastError&&<div className="mt-1 max-w-md text-xs text-red-300">{runtime.lastError}</div>}</div></header>
  <section className="grid grid-cols-2 gap-4 md:grid-cols-4"><Card label="PONs" value={data.pons.length}/><Card label="ONUs" value={total}/><Card label="Online" value={online}/><Card label="Offline" value={total-online}/></section>
  <section className="grid grid-cols-1 gap-4 md:grid-cols-3"><Metric label="Open alerts" value={openAlerts.length} tone={openAlerts.length?'danger':'ok'}/><Metric label="Critical" value={critical} tone={critical?'danger':'ok'}/><Metric label="Warnings" value={warning} tone={warning?'warn':'ok'}/></section>
  <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{data.pons.map(p=><div key={p.id} className="rounded-xl border border-slate-800 bg-slate-900 p-5"><div className="flex items-center justify-between"><b>PON {p.port}</b><span className="rounded-full border border-slate-700 px-2 py-1 text-xs capitalize text-slate-300">{p.status}</span></div><div className="mt-3 text-2xl font-bold">{p.onus.length}</div><div className="text-xs text-slate-500">connected ONUs</div></div>)}</section>
  <section className="overflow-hidden rounded-xl border border-slate-800 bg-slate-900"><div className="flex flex-col gap-3 border-b border-slate-800 p-5 md:flex-row md:items-center md:justify-between"><div><h2 className="font-semibold">Active OLT alerts</h2><p className="mt-1 text-xs text-slate-500">Live alert records generated by the backend optical monitoring engine.</p></div><button onClick={()=>location.reload()} className="rounded-lg border border-slate-700 px-3 py-2 text-xs hover:bg-slate-800">Refresh telemetry</button></div>{openAlerts.length?<div className="divide-y divide-slate-800">{openAlerts.map(a=><div key={a.id} className="flex flex-col gap-2 p-4 md:flex-row md:items-center md:justify-between"><div><div className="font-medium text-slate-200">{a.message}</div><div className="mt-1 text-xs text-slate-500">{a.code} · {a.onu_id||'OLT/PON'} · {new Date(a.last_seen).toLocaleString()}</div></div><span className={`w-fit rounded-full border px-2.5 py-1 text-xs uppercase ${badge(a.severity)}`}>{a.severity}</span></div>)}</div>:<div className="p-8 text-center text-sm text-emerald-300">No open alerts on this OLT.</div>}</section>
  <section className="overflow-hidden rounded-xl border border-slate-800 bg-slate-900"><div className="flex flex-col gap-3 border-b border-slate-800 p-5 md:flex-row md:items-center md:justify-between"><div><h2 className="font-semibold">ONU optical health</h2><p className="mt-1 text-xs text-slate-500">RX/TX power and service state from the OLT hierarchy API. Click a row for its power history.</p></div><select className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All ONUs</option><option value="online">Online</option><option value="offline">Offline</option></select></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead className="bg-slate-950 text-xs uppercase tracking-wide text-slate-500"><tr><th className="p-4 text-left">ONU</th><th className="p-4 text-left">PON</th><th className="p-4 text-left">Serial</th><th className="p-4 text-left">Status</th><th className="p-4 text-left">RX</th><th className="p-4 text-left">TX</th><th className="p-4 text-left">LOS</th></tr></thead><tbody>{onus.length?onus.map(o=><>
   <tr key={o.id} className="cursor-pointer border-t border-slate-800 hover:bg-slate-800/40" onClick={()=>setExpandedOnu(expandedOnu===o.id?null:o.id)}><td className="p-4 font-medium">{o.name}</td><td className="p-4">{o.pon}</td><td className="p-4 font-mono text-xs text-slate-400">{o.serial}</td><td className="p-4 capitalize">{o.status}</td><td className="p-4">{o.rxPowerDbm??'—'} dBm</td><td className="p-4">{o.txPowerDbm??'—'} dBm</td><td className="p-4">{o.los?'Yes':'—'}</td></tr>
   {expandedOnu===o.id&&<tr className="border-t border-slate-800 bg-slate-950/60"><td colSpan={7} className="p-5"><div className="grid gap-6 sm:grid-cols-3"><MetricChart subjectType="onu" subjectId={o.id} metric="rx_power_dbm" label="RX power" unit=" dBm" /><MetricChart subjectType="onu" subjectId={o.id} metric="tx_power_dbm" label="TX power" unit=" dBm" /><MetricChart subjectType="onu" subjectId={o.id} metric="distance_meters" label="Distance" unit="m" formatValue={v=>v.toFixed(0)} /></div></td></tr>}
  </>):<tr><td colSpan={7} className="p-8 text-center text-slate-500">No ONUs match this filter.</td></tr>}</tbody></table></div></section>
 </main>
}
function Card({label,value}:{label:string;value:number}){return <div className="rounded-xl border border-slate-800 bg-slate-900 p-5"><div className="text-sm text-slate-500">{label}</div><div className="mt-2 text-3xl font-bold">{value}</div></div>}
function Metric({label,value,tone}:{label:string;value:number;tone:'danger'|'warn'|'ok'}){const c=tone==='danger'?'text-red-300':tone==='warn'?'text-amber-300':'text-emerald-300';return <div className="rounded-xl border border-slate-800 bg-slate-900 p-5"><div className="text-sm text-slate-500">{label}</div><div className={`mt-2 text-3xl font-bold ${c}`}>{value}</div></div>}
