#!/usr/bin/env bash
set -Eeuo pipefail
APP_DIR="/opt/routingnms"; APP_USER="routingnms"; API_PORT="8080"; WEB_PORT="3000"; REPO_URL="${ROUTINGNMS_REPO_URL:-https://github.com/ihtishamshahzad7/RoutingNMS.git}"
log(){ printf '\n[%s] %s\n' "$(date '+%H:%M:%S')" "$*"; }
dump_service_diagnostics(){ for svc in routingnms-api routingnms-web nginx; do printf '\n----- systemctl status %s -----\n' "$svc"; systemctl status "$svc" --no-pager -l 2>&1 || true; printf '\n----- journalctl -u %s (last 40 lines) -----\n' "$svc"; journalctl -u "$svc" -n 40 --no-pager 2>&1 || true; done; }
fail(){ echo "ERROR: $*" >&2; dump_service_diagnostics; exit 1; }
[[ "$(id -u)" -eq 0 ]] || fail "Run as root (sudo -i)."; [[ -d "$APP_DIR/.git" ]] || fail "$APP_DIR is not a Git checkout. Run install.sh first."
log "Pulling latest RoutingNMS code"; git -c safe.directory="$APP_DIR" -C "$APP_DIR" remote set-url origin "$REPO_URL"; git -c safe.directory="$APP_DIR" -C "$APP_DIR" fetch origin; GIT_OLD="$(git -c safe.directory="$APP_DIR" -C "$APP_DIR" rev-parse HEAD)"; git -c safe.directory="$APP_DIR" -C "$APP_DIR" reset --hard origin/main; GIT_NEW="$(git -c safe.directory="$APP_DIR" -C "$APP_DIR" rev-parse HEAD)"; printf 'Updated %s -> %s\n' "${GIT_OLD:0:12}" "${GIT_NEW:0:12}"
log "Synchronizing Go dependencies and building backend"; cd "$APP_DIR/backend"; go mod tidy; go mod download; go mod verify; CGO_ENABLED=0 go build -buildvcs=false -trimpath -ldflags="-s -w" -o "$APP_DIR/routingnms-api" ./cmd/api
if [[ -f "$APP_DIR/frontend/package.json" ]]; then log "Installing frontend dependencies and building Next.js"; cd "$APP_DIR/frontend"; if [[ -f package-lock.json ]]; then npm ci --include=dev --no-audit --no-fund; else npm install --include=dev --no-audit --no-fund; fi; npm run build; CSS_FILE="$(find .next/static/css -maxdepth 1 -name '*.css' -print -quit 2>/dev/null || true)"; [[ -n "$CSS_FILE" ]] || fail "Next.js build produced no CSS file."; CSS_BYTES="$(wc -c < "$CSS_FILE")"; [[ "$CSS_BYTES" -ge 1000 ]] || fail "Generated CSS is only ${CSS_BYTES} bytes; Tailwind/PostCSS did not compile correctly."; log "Generated CSS OK (${CSS_BYTES} bytes): $CSS_FILE"; fi
log "Applying PostgreSQL migrations"; if [[ -d "$APP_DIR/backend/migrations" ]]; then shopt -s nullglob; migrations=($(printf '%s\n' "$APP_DIR/backend/migrations"/*.sql | sort -V)); for migration in "${migrations[@]}"; do log "Applying $(basename "$migration")"; sudo -u postgres psql -d routingnms -v ON_ERROR_STOP=1 -f "$migration"; done; sudo -u postgres psql -d routingnms -v ON_ERROR_STOP=1 -c "GRANT USAGE ON SCHEMA public TO ${APP_USER}; GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ${APP_USER}; GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO ${APP_USER}; ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO ${APP_USER}; ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO ${APP_USER};"; fi
[[ -f "$APP_DIR/backend/migrations/0007_device_snmp.sql" ]] || fail "SNMP device migration 0007_device_snmp.sql is missing from this deployment."
[[ -f "$APP_DIR/backend/migrations/0008_device_interfaces.sql" ]] || fail "Device interface migration 0008_device_interfaces.sql is missing from this deployment."
log "Installing current systemd and Nginx configuration"; install -m 0644 "$APP_DIR/deployments/ubuntu-24.04/routingnms-api.service" /etc/systemd/system/routingnms-api.service; install -m 0644 "$APP_DIR/deployments/ubuntu-24.04/routingnms-web.service" /etc/systemd/system/routingnms-web.service; install -m 0644 "$APP_DIR/deployments/ubuntu-24.04/nginx.conf" /etc/nginx/sites-available/routingnms; ln -sfn /etc/nginx/sites-available/routingnms /etc/nginx/sites-enabled/routingnms; rm -f /etc/nginx/sites-enabled/default; nginx -t; systemctl daemon-reload; systemctl enable --now routingnms-api routingnms-web nginx; systemctl restart routingnms-api routingnms-web; systemctl reload nginx
log "Checking API and frontend"; wait_for_api(){ local tries=15; for ((i=1;i<=tries;i++)); do if curl -fsS "http://127.0.0.1:${API_PORT}/api/v1/health" >/dev/null 2>&1; then return 0; fi; systemctl is-active --quiet routingnms-api || fail "routingnms-api exited after restart."; sleep 1; done; fail "routingnms-api did not respond within ${tries}s."; }; wait_for_api; curl -fsS "http://127.0.0.1:${API_PORT}/api/v1/health" | jq .; curl -fsS "http://127.0.0.1:${API_PORT}/api/v1/ready" | jq .; curl -fsSI "http://127.0.0.1:${WEB_PORT}/" | head -n 12
log "Checking Next.js static CSS and JavaScript through Nginx"; HTML="$(curl -fsS http://127.0.0.1:${WEB_PORT}/)"; CSS_PATH="$(printf '%s' "$HTML" | grep -oE '/_next/static/[^\" ]+\.css' | head -n1 || true)"; JS_PATH="$(printf '%s' "$HTML" | grep -oE '/_next/static/[^\" ]+\.js' | head -n1 || true)"; [[ -n "$CSS_PATH" ]] || fail "No CSS asset found in HTML."; [[ -n "$JS_PATH" ]] || fail "No JavaScript asset found in HTML."; CSS_HEADERS="$(curl -fsSI "http://127.0.0.1${CSS_PATH}")" || fail "CSS asset unavailable: ${CSS_PATH}"; JS_HEADERS="$(curl -fsSI "http://127.0.0.1${JS_PATH}")" || fail "JavaScript asset unavailable: ${JS_PATH}"; printf '%s\n' "$CSS_HEADERS" | head -n 12; printf '%s\n' "$JS_HEADERS" | head -n 12; printf '%s\n' "$CSS_HEADERS" | grep -qi '200 OK' || fail "CSS did not return HTTP 200"; printf '%s\n' "$JS_HEADERS" | grep -qi '200 OK' || fail "JavaScript did not return HTTP 200"; printf '%s\n' "$CSS_HEADERS" | grep -qi 'text/css' || fail "CSS Content-Type is wrong"
log "Checking authentication endpoint"; curl -fsS -o /dev/null -w '%{http_code}' "http://127.0.0.1:${API_PORT}/api/v1/auth/me" | grep -qE '^(200|401)$' || fail "auth/me did not respond as expected."
for svc in routingnms-api routingnms-web nginx; do systemctl is-active --quiet "$svc" || fail "Service $svc is not active."; done
SERVER_IP="$(hostname -I | awk '{print $1}')"; [[ -n "$SERVER_IP" ]] || SERVER_IP="SERVER-IP"
printf '\n==================================================\nRoutingNMS UPDATE COMPLETE\n==================================================\nVersion: %s\n\nBrowser: http://%s/\nDashboard: http://%s/dashboard\nDevices: http://%s/devices\nAPI: http://%s:%s\n\nDefault username: admin\nDefault password: admin123\n(change after first login)\n\nServices: API OK | Web OK | Nginx OK\nPostgreSQL: OK\nFrontend CSS: OK\nFrontend JS: OK\nDevice SNMP configuration: INCLUDED\nPer-device SNMP API: INCLUDED\nDevice interface discovery: INCLUDED\nDevice monitor page: http://%s/devices/<device-id>\n==================================================\n\n' "$GIT_NEW" "$SERVER_IP" "$SERVER_IP" "$SERVER_IP" "$SERVER_IP" "$API_PORT" "$SERVER_IP"