ALTER TABLE devices
    ADD COLUMN IF NOT EXISTS snmp_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS snmp_version TEXT NOT NULL DEFAULT '2c',
    ADD COLUMN IF NOT EXISTS snmp_community TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS snmp_username TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS snmp_auth_protocol TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS snmp_auth_password TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS snmp_priv_protocol TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS snmp_priv_password TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS snmp_port INTEGER NOT NULL DEFAULT 161,
    ADD COLUMN IF NOT EXISTS snmp_timeout_ms INTEGER NOT NULL DEFAULT 3000;

CREATE INDEX IF NOT EXISTS idx_devices_snmp_enabled ON devices(snmp_enabled);
