"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { useEffect, useState } from "react";
import { ApiError, apiFetch } from "../../../../lib/api";

type Device={id:string;name:string;address:string;deviceType:string;vendor?:string;enabled:boolean;snmpEnabled:boolean;snmpVersion:string;snmpPort:number;snmpConfigured:boolean};
type Interface={id:number;deviceId:string;ifIndex:number;name:string;description:string;adminUp:boolean;operUp:boolean;inOctets:number;outOctets:number;inErrors:number;outErrors:number;lastDiscoveredAt?:string};

const ORG="tenant-1";
const card="rounded-2xl border border-slate-800 bg-slate-900 p-5";

export default function DeviceDetailsPage(){
 const params=useParams<{id:string}>(); const id=params.id;
 const [device,setDevice]=useState<Device|null>(null),[interfaces,setInterfaces]=useState<Interface[]>([]),[loading,setLoading]=useState(true),[discovering,setDiscovering]=useState(false),[message,setMessage]=useState("");
 async function load(){setLoading(true);try{const devices=await apiFetch<Device[]>(`/devices?organizationId=${ORG}`);const d=devices.find(x=>x.id===id);if(!d)throw new Error("Device not found");setDevice(d);setInterfaces(await apiFetch<Interface[]>(`/devices/${id}/interfaces`))}catch(e){setMessage(e instanceof ApiError?e.message:e instanceof Error?e.message:"Unable to load device")}finally{setLoading(false)}}
 useEffect(()=>{load()},[id]);
 async function discover(){setDiscovering(true);setMessage("");try{const r=await apiFetch<{interfaceCount:number;systemName?:string}>(`/devices/${id}/discover`,{method:"POST"});setMessage(`Discovery completed: ${r.interfaceCount} interfaces saved${r.systemName?` · ${r.systemName}`:""}.`);await load()}catch(e){setMessage(e instanceof ApiError?e.message:e instanceof Error?e.message:"SNMP discovery failed")}finally{setDiscovering(false)}}
 if(loading)return <main className="mx-auto max-w-7xl px-6 py-8 text-slate-400">Loading device…</main>;
 if(!device)return <main className="mx-auto max-w-7xl px-6 py-8"><div className={card}><h1 className="text-xl font-semibold">Device unavailable</h1><p className="mt-2 text-sm text-slate-400">{message||"The requested device does not exist."}</p><Link href="/devices" className="mt-4 inline-block text-cyan-400">← Back to devices</Link></div></main>;
 const up=interfaces.filter(x=>x.operUp).length;
 return <main className="mx-auto max-w-7xl px-6 py-8"><div className="mb-6 flex flex-wrap items-start justify-between gap-4"><div><Link href="/devices" className="text-xs text-slate-500 hover:text-cyan-400">← Network Devices</Link><div className="mt-3 text-xs font-semibold tracking-[.2em] text-cyan-400">DEVICE MONITORING</div><h1 className="mt-1 text-3xl font-bold">{device.name}</h1><p className="mt-1 text-sm text-slate-400">{device.address} · {device.vendor||device.deviceType}</p></div><button onClick={discover} disabled={discovering||!device.snmpEnabled} className="rounded-xl bg-cyan-600 px-5 py-3 text-sm font-semibold text-white disabled:cursor-not-allowed disabled:opacity-40">{discovering?"Discovering…":"Run SNMP Discovery"}</button></div>{message&&<div className="mb-5 rounded-xl border border-cyan-900 bg-cyan-950/30 px-4 py-3 text-sm text-cyan-200">{message}</div>}
 <section className="mb-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div className={card}><div className="text-xs uppercase text-slate-500">SNMP</div><div className="mt-2 text-xl font-bold">{device.snmpEnabled?`Enabled · v${device.snmpVersion}`:"Disabled"}</div><div className="mt-1 text-xs text-slate-500">Port {device.snmpPort}</div></div><div className={card}><div className="text-xs uppercase text-slate-500">Interfaces</div><div className="mt-2 text-xl font-bold">{interfaces.length}</div><div className="mt-1 text-xs text-emerald-400">{up} operationally up</div></div><div className={card}><div className="text-xs uppercase text-slate-500">Errors</div><div className="mt-2 text-xl font-bold">{interfaces.reduce((n,x)=>n+x.inErrors+x.outErrors,0)}</div><div className="mt-1 text-xs text-slate-500">Across discovered interfaces</div></div><div className={card}><div className="text-xs uppercase text-slate-500">Monitoring</div><div className="mt-2 text-xl font-bold">{device.enabled?"Enabled":"Disabled"}</div><div className="mt-1 text-xs text-slate-500">Live inventory view</div></div></section>
 <section className={card}><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">Interface inventory</h2><p className="mt-1 text-xs text-slate-500">IF-MIB data discovered from the device and persisted in PostgreSQL.</p></div><button onClick={load} className="rounded-lg border border-slate-700 px-3 py-2 text-xs hover:bg-slate-800">Refresh</button></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="border-b border-slate-800 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-3 py-3">Index</th><th>Name</th><th>Description</th><th>Admin</th><th>Oper</th><th>In errors</th><th>Out errors</th><th>Last discovery</th></tr></thead><tbody>{interfaces.length?interfaces.map(x=><tr key={x.id} className="border-b border-slate-800/70"><td className="px-3 py-3 text-slate-500">{x.ifIndex}</td><td className="font-medium">{x.name||"—"}</td><td className="text-slate-400">{x.description||"—"}</td><td><span className={x.adminUp?"text-emerald-400":"text-slate-500"}>{x.adminUp?"UP":"DOWN"}</span></td><td><span className={x.operUp?"text-emerald-400":"text-red-400"}>{x.operUp?"UP":"DOWN"}</span></td><td>{x.inErrors}</td><td>{x.outErrors}</td><td className="text-xs text-slate-500">{x.lastDiscoveredAt?new Date(x.lastDiscoveredAt).toLocaleString():"—"}</td></tr>):<tr><td colSpan={8} className="py-12 text-center text-slate-500">No interface inventory yet. Click <b>Run SNMP Discovery</b> to discover and save interfaces.</td></tr>}</tbody></table></div></section></main>
}
