"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { apiFetch, ApiError } from "../../../lib/api";
import BackendSync from "./backend-sync";

type RuntimeState={oltId:string;running:boolean;startedAt?:string;lastPollAt?:string;lastError?:string;pollCount:number};
type Alert={id:number;oltId:string;ponId:string;onuId:string;code:string;severity:string;message:string;status:string;lastSeen:string};
type DeviceHealth={id:string;name:string;address:string;deviceType:string;vendor?:string;method:"SNMP"|"TCP";reachable:boolean;latencyMs:number;checkedAt:string;error?:string};
const ORG="tenant-1";
function formatTime(v?:string){return v?new Date(v).toLocaleString():"—"}

export default function DashboardPage(){
 const router=useRouter();const [states,setStates]=useState<RuntimeState[]>([]);const [alerts,setAlerts]=useState<Alert[]>([]);const [health,setHealth]=useState<DeviceHealth[]>([]);const [healthLoading,setHealthLoading]=useState(true);
 const loadHealth=async()=>{setHealthLoading(true);try{setHealth(await apiFetch<DeviceHealth[]>(`/devices/health?organizationId=${ORG}`))}catch(e){if(e instanceof ApiError&&e.status===401)router.replace("/")}finally{setHealthLoading(false)}};
 useEffect(()=>{let active=true;const load=async()=>{try{const data=await apiFetch<{olts:RuntimeState[]}>("/olt/runtime");if(active)setStates(Array.isArray(data.olts)?data.olts:[])}catch(e){if(active&&e instanceof ApiError&&e.status===401)router.replace("/")}};load();loadHealth();const t=window.setInterval(()=>{load();loadHealth()},15000);return()=>{active=false;window.clearInterval(t)}},[router]);
 useEffect(()=>{let active=true;const load=async()=>{const results=await Promise.all(states.filter(s=>s.oltId).map(async s=>{try{const r=await fetch(`/api/v1/olts/${encodeURIComponent(s.oltId)}/alerts?limit=10`,{cache:"no-store"});return r.ok?await r.json():[]}catch{return[]}}));if(active)setAlerts(results.flat().filter((a:Alert)=>a.status==="open").slice(0,20))};if(states.length)load();else setAlerts([]);return()=>{active=false}},[states]);
 const running=states.filter(s=>s.running).length;const critical=alerts.filter(a=>a.severity.toLowerCase()==="critical").length;const healthy=health.filter(d=>d.reachable).length;const totalPolls=useMemo(()=>states.reduce((n,s)=>n+s.pollCount,0),[states]);
 return <main className="mx-auto max-w-7xl px-6 py-8"><div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold tracking-[.2em] text-cyan-400">LIVE NOC</p><h1 className="mt-2 text-3xl font-bold">Network Overview</h1><p className="mt-2 text-sm text-slate-400">One operational view for device reachability, SNMP monitoring, OLT runtime and incidents.</p></div><button onClick={loadHealth} disabled={healthLoading} className="rounded-lg border border-slate-700 px-4 py-2 text-sm hover:bg-slate-800 disabled:opacity-50">{healthLoading?"Checking devices…":"Check devices now"}</button></div>
 <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><article className="rounded-xl border border-slate-800 bg-slate-900 p-5"><div className="text-sm text-slate-400">Device Health</div><div className="mt-2 text-3xl font-semibold">{health.length?`${healthy}/${health.length}`:"—"}</div><div className="mt-2 text-xs text-slate-500">Reachable devices</div></article><article className="rounded-xl border border-slate-800 bg-slate-900 p-5"><div className="text-sm text-slate-400">OLT Pollers</div><div className="mt-2 text-3xl font-semibold">{running}</div><div className="mt-2 text-xs text-slate-500">{totalPolls} polls completed</div></article><article className="rounded-xl border border-slate-800 bg-slate-900 p-5"><div className="text-sm text-slate-400">Critical Alerts</div><div className="mt-2 text-3xl font-semibold">{critical}</div><div className="mt-2 text-xs text-slate-500">{critical?"Immediate attention required":"No active critical alerts"}</div></article><article className="rounded-xl border border-slate-800 bg-slate-900 p-5"><div className="text-sm text-slate-400">Open Alerts</div><div className="mt-2 text-3xl font-semibold">{alerts.length}</div><div className="mt-2 text-xs text-slate-500">{alerts.length?"Active incidents":"No active incidents"}</div></article></div>
 <section className="mt-6 rounded-2xl border border-slate-800 bg-slate-900 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">Device health</h2><p className="mt-1 text-xs text-slate-500">Live backend probes. SNMP-enabled devices are checked through their configured SNMP endpoint; other devices use TCP reachability.</p></div><Link href="/devices" className="text-xs text-cyan-400">Manage devices →</Link></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b border-slate-800 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-3 py-3">Device</th><th>Address</th><th>Method</th><th>Status</th><th>Latency</th><th>Checked</th></tr></thead><tbody>{health.length?health.map(d=><tr key={d.id} className="border-b border-slate-800/70"><td className="px-3 py-3"><Link href={`/devices/${d.id}`} className="font-medium text-cyan-400 hover:underline">{d.name}</Link><div className="text-xs text-slate-500">{d.vendor||d.deviceType}</div></td><td className="text-slate-300">{d.address}</td><td><span className="rounded-full bg-slate-800 px-2 py-1 text-xs text-slate-300">{d.method}</span></td><td><span className={`rounded-full px-2 py-1 text-xs ${d.reachable?"bg-emerald-950 text-emerald-300":"bg-red-950 text-red-300"}`}>{d.reachable?"Reachable":"Down"}</span>{d.error&&<div className="mt-1 max-w-xs truncate text-xs text-red-300" title={d.error}>{d.error}</div>}</td><td className="text-slate-300">{d.latencyMs.toFixed(1)} ms</td><td className="text-xs text-slate-500">{formatTime(d.checkedAt)}</td></tr>):<tr><td colSpan={6} className="py-10 text-center text-slate-500">{healthLoading?"Checking registered devices…":"No registered devices yet."}</td></tr>}</tbody></table></div></section>
 <div className="mt-6 grid gap-6 lg:grid-cols-3"><section className="rounded-xl border border-slate-800 bg-slate-900 p-5 lg:col-span-2"><div className="flex justify-between"><h2 className="font-semibold">OLT Runtime</h2><Link href="/olts" className="text-xs text-cyan-400">Manage OLTs →</Link></div><div className="mt-4 space-y-2">{states.length?states.map(s=><div key={s.oltId} className="rounded-lg border border-slate-800 p-4"><div className="flex items-center justify-between"><div className="font-medium">{s.oltId}</div><span className={`rounded-full px-2 py-1 text-xs ${s.running?"bg-emerald-950 text-emerald-300":"bg-slate-800 text-slate-400"}`}>{s.running?"Running":"Stopped"}</span></div><div className="mt-2 grid gap-2 text-xs text-slate-500 sm:grid-cols-3"><span>Polls: {s.pollCount}</span><span>Last poll: {formatTime(s.lastPollAt)}</span><span>{s.lastError?`Error: ${s.lastError}`:"Healthy"}</span></div></div>):<div className="flex min-h-32 items-center justify-center rounded-lg border border-dashed border-slate-800 text-sm text-slate-500">No OLT runtime data available. <Link href="/olts" className="ml-1 text-cyan-400">Add an OLT</Link></div>}</div></section><section className="rounded-xl border border-slate-800 bg-slate-900 p-5"><h2 className="font-semibold">Active Alerts</h2><div className="mt-4 space-y-2">{alerts.length?alerts.map(a=><div key={a.id} className="rounded-lg border border-slate-800 p-3"><div className="flex items-center justify-between gap-2"><span className="text-xs font-semibold uppercase">{a.severity}</span><span className="text-xs text-slate-500">{a.oltId}</span></div><div className="mt-1 text-sm">{a.message}</div><div className="mt-1 text-xs text-slate-500">{a.onuId||a.ponId||a.code} · {formatTime(a.lastSeen)}</div></div>):<div className="rounded-lg border border-slate-800 p-4 text-sm text-slate-400">No active alerts.</div>}</div></section></div>
 <section className="mt-6 rounded-xl border border-slate-800 bg-slate-900 p-5"><h2 className="font-semibold">Infrastructure</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Link href="/devices" className="rounded-lg bg-slate-950 p-4 hover:bg-slate-900"><div className="text-sm text-slate-400">Routers / Switches</div><div className="mt-1 text-sm text-cyan-400">Manage devices →</div></Link><Link href="/devices" className="rounded-lg bg-slate-950 p-4 hover:bg-slate-900"><div className="text-sm text-slate-400">SNMP</div><div className="mt-1 text-sm text-cyan-400">Configure & monitor →</div></Link><Link href="/olts" className="rounded-lg bg-slate-950 p-4 hover:bg-slate-900"><div className="text-sm text-slate-400">OLTs</div><div className="mt-1 text-sm text-cyan-400">Configure →</div></Link><Link href="/incidents" className="rounded-lg bg-slate-950 p-4 hover:bg-slate-900"><div className="text-sm text-slate-400">Incidents</div><div className="mt-1 text-sm text-cyan-400">View alerts →</div></Link></div></section><BackendSync /></main>
}
